#library(ggtern)
library(Ternary)
library(hrbrthemes)
library(ggplot2)
library(DirichletReg)
library(DescTools)
library(TCC)
library(psych)
library(scales)
library(devEMF)
library(rgl)
library(magick)

source('Cosbin_functions.R')
source('Cosbin_functions_visualization.R')
source('Cosbin_functions_evaluation.R')

set.seed(17)